management:
  health:
    diskspace:
      enabled: false
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

occam:
  lti:
    ultra:
      issuer: https://blackboard.com
      authorization-host: https://developer.blackboard.com
      application-id: <application-id>
      host: <host>